### ISSUE TITLE
Document (possibly uneven) allocation of consumers to shards

### ISSUE THREAD

**Issue by sumitdev** [rabbitmq/rabbitmq-sharding#11]
I have created a sharding policy with 100 shards, the queues are not getting evenly divided among consumers. Instead they are randomly allocated, with some queues getting 10, and few not getting even 1. 

Configuration:

`rabbitmqctl set_policy images-shard "^ShardedExchange$" '{"shards-per-node": 100, "routing-key": "test"}'`

Spring-AMQP client 

	<rabbit:listener-container id="workQueueListenerContainer" connection-factory="consumerConnectionFactory" 
			 acknowledge="auto" concurrency="100">
		<rabbit:listener ref="workListener" method="onMessage" queue-names="ShardedExchange" admin="rabbitWorkAdmin" />
	</rabbit:listener-container>

I have tried this with different partition counts, the issue is observed in all. Once running with 1000 partitions/consumers, one queue ended with 500 consumers.

**Comment by michaelklishin** [comment]
While I doubt this has anything to do with the client, we'd appreciate if you could check if the issue remains with any other client (e.g. the Java one).

**Comment by videlalvaro** [comment]
This undesirable but expected behavior. This question has been answered either on a closed issue here or on the mailing list. I'm on holidays right now but I'll see to get this documented in case it's not already.

**Comment by sumitdev** [comment]
But the documentation says "The plugin will chose the queue from the shard with the least amount of consumers, provided the queue contents are local to the broker you are connected to.".  I guess the documentation is wrong in that case.

**Comment by videlalvaro** [comment]
See https://github.com/rabbitmq/rabbitmq-sharding/issues/7 for an explanation. 
The documentation is not wrong, the DB that tracks consumers has to be updated and that takes time, even if a few milliseconds. There's a race condition between your basic_consume comands and those DB updates

**Comment by michaelklishin** [comment]
@sumitdev which means if you spread consumer registration over time, the distribution should be much more even. I'm not sure if spring-amqp allows for that but when scaling up in a realistic system, chances are you won't add 1000 shards and consumers at once, more like 10 at a time every N minutes.

**Comment by sumitdev** [comment]
I can confirm the behavior remains same with java client without pausing between basic.consume calls. But the problem doesn't occur if I put a 2 sec sleep between them. So it is as you say. 

Only the documentation needs to be fixed in that case. Though, if the race condition could be avoided with synchronization, it would be great!

**Comment by sumitdev** [comment]
@michaelklishin Let me also, quite humbly, correct you on one account, namely that a statement in documentation *can not mean* something which it *does not state*, so the knowledge "which means if you spread consumer registration over time, the distribution should be much more even" can't possibly be derived from the original, by anyone except the authors.

**Comment by michaelklishin** [comment]
You are correct :)

**Comment by videlalvaro** [comment]
I added a note on the README
