### ISSUE TITLE
Ha queues, failover and consuming

### ISSUE THREAD

**Issue by nfillot** [rabbitmq/rabbitmq-sharding#12]
Hello,

I am using rabbitmq-sharding plugin with ha queues.
My sharding queues are correctly created on both of my nodes and i can consume from all my shards.

When i simulate the failure of a node, the sync of messages is correctly done but i can't consume the messages that were on that node.

From what i saw in the interceptor, it's because we only consume from queues that were created locally

```erlang
least_consumers(VHost, QBin, N) ->
    F = fun(QNum) ->
                QBin2 = rabbit_sharding_util:make_queue_name(
                          QBin, a2b(node()), QNum),
                case consumer_count(r(VHost, queue, QBin2)) of
                    {error, E}       -> {error, E};
                    [{consumers, C}] -> {C, QBin2}
                end
```
Am i mistaken ? If not, how can i proceed to be able to consume the messages in case of a failover ?

Thanks

**Comment by michaelklishin** [comment]
@nfillot a client can consume from a queue hosted on any node, from any node. With "regular" queues,
as of 3.4.0 consumers will be re-added if they consume from a mirror and master is relocated due to a node failure. In other cases, a consumer cancellation notification need to be handled to re-consume.

So chances are, this is the reason for that. Can you be more specific with how you conduct your experiment than "I can't consume the messages that were on that node"?

**Comment by nfillot** [comment]
@michaelklishin 
Yes no problem

So i have two shards per node (and two nodes), let's say :

 shard: - nodename1 images 1
 shard: - nodename1 images 2
 shard: - nodename2 images 1
 shard: - nodename2 images 2. 

I am doing some publishing on an exchange named images.test and with random routing_keys.
Every shard is getting messages (so both nodes)

I launch a consumer on each node (basic.consume on images.test), here is the following python quick&dirty snippet
```python
from haigha.connection import Connection
from haigha.message import Message
import logging
logging.basicConfig()

def consumer(msg):
  print msg
 
connection = Connection(
  user='admin', password="",
  vhost='img', host='192.168.1.1',
  heartbeat=None, debug=True)

ch = connection.channel()
while True:
  ch.basic.consume('images.test', consumer)
```

I am able to retrieve every messages :
Consumer connecting on nodename1 is getting messages of shards located on nodename1
Consumer connecting on nodename2 is getting messages of shards located on nodename2

Looks good  and validates the following statement : 
```
The advantage of this setup is that the queues from where your consumers will get messages will be local to the node where they are connected.
```
But, if nodename1 is down and if i start my consuming program (so no problem of consumer cancellation here), i can get messages of the following shards

 shard: - nodename2 images 1
 shard: - nodename2 images 2. 

But not from shards located in nodename1 despite the good sync of nodename1 shards on nodename2

**Comment by videlalvaro** [comment]
If a node is down then you can't get messages from that node. This problem
is not related with Sharding. Also the sharding plugin doesn't perform
rebalancing/message migration. It mostly does message stream partitioning.

**Comment by nfillot** [comment]
```
If a node is down then you can't get messages from that node.
```
Yes sure. 
But when you're doing mirrored queues (with rabbitmq-sharding), one can assume you still can get messages (shards being synchronized to the other node). Am i wrong ?

**Comment by videlalvaro** [comment]
My bad, I understand your question now.

When you issue a basic_consume to a sharded queue, the plugin must build the queue name based on certain parameters, like shard name, node name, and queue index. The node name is always the local node name, even if there's a queue which has a replica on the current node.

At the moment I can't see a "good" solution to said problem, so the only thing you could do is to explicitly consume from your other queues, say:

```
channel.basic_consume("shard: - nodename1 images 1");
```

**Comment by nfillot** [comment]
That's what i thought. Doing this or via the API.
Thanks for confirming this.

**Comment by macmk** [comment]
Any changes since original post? I'l like to use sharding plugin, but as I understand, it will partially break (not use) high availability configuration.

**Comment by michaelklishin** [comment]
@macmk there were no significant changes. Sharded queues use "regular" queues under the hood, which means policies can be applied to shards once you figure out the naming pattern. Mirroring shards will to some extent defeat the goal (parallelisation and distribution) of this plugin but it's certainly not impossible.

Please post your questions to rabbitmq-users in the future. This team does not use GitHub issues for questions, discussions, investigations and such.
