### ISSUE TITLE
Message Durability in the Shards

### ISSUE THREAD

**Issue by VladimirMakaev** [rabbitmq/rabbitmq-sharding#26]
If I understand correctly the setup with sharding plugin the queues are not durable. So potentially we have a problem that in the case a node goes down in the cluster we can loose messages that haven't been consumed yet in that shard.

Would be useful to have system relying on this plugin to be able to survive the node restart without message lost or maybe somehow take advantage of the queues mirroring.

**Comment by michaelklishin** [comment]
Individual shards' durability [directly depends on that of the exchange they are bound to](https://github.com/rabbitmq/rabbitmq-sharding/blob/eb831d18f05fc65293e6682ef0dcf56f2c986117/src/rabbit_sharding_shard.erl#L79).
