### ISSUE TITLE
High Availability support

### ISSUE THREAD

**Issue by jlisickigog** [rabbitmq/rabbitmq-sharding#34]
When HA (ha-mode) is applied to a sharded queues, everything works fine when original node for a sharded queue is up. When its down, it is not possible to consume messages even if other node is elected as a master for this sharded queue. From my understanding, it happens because the name of the current node (name of the node to which the consumer is connected) is added to the name of virtual queue to compose sharded queue name when consumer is attached to queue. 

Is there any plan to make this plugin HA compliant?

**Comment by michaelklishin** [comment]
Queue name has no effect on its mirroring. "Virtual queues" can be made mirrored already using a policy. There are no plans to significantly change the way this plugin works. If this changes, we will file a new issue with a more specific set of goals.

**Comment by michaelklishin** [comment]
It's also worth noting that the goal of this plugin is to spread queue operation flow across N node (partition it). This is largely at odds with replication. Mirroring the "shards" naively would reduce total throughput, not increase it, and even mirroring to a quorum might be a net negative. Addressing most of those issues is not in scope for this plugin (or possibly any plugin).
