### ISSUE TITLE
when publishing one message to sharded exchange, I see the message in all queues not just in one of the shards

### ISSUE THREAD

**Issue by javiervegas** [rabbitmq/rabbitmq-sharding#4]
Steps to reproduce:

1) Install rabbitmq 3.4.3 with rabbitmq_management, rabbitmq-sharding and rabbitmq_consistent_hash_exchange plugins enabled
![plugins](https://cloud.githubusercontent.com/assets/63576/5953705/79cb5d38-a742-11e4-9b46-15d1c8951938.png)
2) Add a exchange with a sharded policy:
<pre>
rabbitmqctl set_policy images-shard "^shard.images$" '{"shards-per-node": 2, "routing-key": "1234"}'
</pre>
![policy](https://cloud.githubusercontent.com/assets/63576/5953711/826cb892-a742-11e4-80e8-ceb6f49d0478.png)
3) verify sharded queues are automatically created 
![exchange](https://cloud.githubusercontent.com/assets/63576/5953713/8d329b7a-a742-11e4-90e7-1e040749bb61.png)
4) Use the management UI to publish a message to the exchange with the sharding (1234) routing key ![publish](https://cloud.githubusercontent.com/assets/63576/5953721/9a8cb634-a742-11e4-9592-3f348e90e5de.png)

Expected result:

Only one of the automatically created queues will have 1 message, the other(s) will be empty

Observed result:

All the automatically created queues have 1 message 

![mesages](https://cloud.githubusercontent.com/assets/63576/5953724/a09cd05e-a742-11e4-9789-3cf06d150e01.png)

I am missing anything to get the sharding working so messages arrive to just one of the sharded queues?

Thanks!

**Comment by michaelklishin** [comment]
This repository is a mirror but this is detailed enough to keep here and not move to rabbitmq-users. The author is this plugin is attending a conference in the next few days. He'll respond as time permits.

**Comment by videlalvaro** [comment]
What's the type of the exchange used? For a message to end in only one
queue you either need to use the consistent-hashing exchange or the
modulus-hash exchange. The later is provided with the sharding plugin and
might be faster than the consistent one.

**Comment by videlalvaro** [comment]
I see it now. You are using a direct exchange, this won't work so well. I
think this is documented in one of the READMEs
