### ISSUE TITLE
Unable to consume from sharded "pseudo" queue

### ISSUE THREAD

**Issue by julienbonastre** [rabbitmq/rabbitmq-sharding#42]
I am unsure as to why this occurs but I receive a 404 NOT_FOUND Fault trying to connect a consumer to this queue (via Python Pika 1.1.0 package)

Is this an issue related to pika specifically or the way in which RMQ shard plugin is not handling the amqp consumer "basic consume" request?
![image](https://user-images.githubusercontent.com/71309253/94778481-b4881a00-0408-11eb-97cc-805c3695619e.png)

![image](https://user-images.githubusercontent.com/71309253/94778416-8e627a00-0408-11eb-916d-f93b7352a51c.png)

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.
