### ISSUE TITLE
Make routing-key optional

### ISSUE THREAD

**Issue by videlalvaro** [rabbitmq/rabbitmq-sharding#6]
- Make the routing-key policy optional.
- Document how it works when certain exchanges might expect a routing key.
- Improve current docs to make clear the routing-key behaviour

**Comment by michaelklishin** [comment]
All tests fail on stable, so I assume this tracks master only now => `3.6.0`.

**Comment by videlalvaro** [comment]
For me rabbitmq-sharding stable against rabbitmq-server stable pass. The same with master & master

**Comment by michaelklishin** [comment]
OK then. This was submitted against `master`.

**Comment by videlalvaro** [comment]
yep, since behaviour changed I submitted against master for 3.6.0
