### ISSUE TITLE
Ensure I consume from all queues

### ISSUE THREAD

**Issue by stefansedich** [rabbitmq/rabbitmq-sharding#7]
How can I ensure that I consume from all of the queues? if I spin up 8 threads all consuming from the logical queue "events" they might not connect to all of the shards and I might not get all the messages.

Do I need to resort to connecting to the explicit shards manually?

Cheers

**Comment by videlalvaro** [comment]
Every time you add a consumer to RabbitMQ, state needs to be updated inside the queue process to know there's a new consumer, and that takes time, therefore when you add the second consumer, said state might not be up to date, yet.

So the solution here is to add a small delay between each basicConsume call, so the queue has had time to catchup to the consumer that was just added.

**Comment by julienbonastre** [comment]
How long a delay? a few secs? a few mins?

**Comment by michaelklishin** [comment]
Starting "shards" takes a fraction of a second in most cases. On nodes really strapped on CPU resources it can take a few seconds but that's not a baseline scenario.
