### ISSUE TITLE
hash is wrong

### ISSUE THREAD

**Issue by luzi2000** [rabbitmq/rabbitmq-sharding#8]
I make one shard, ten queues and ten consumers. I make data and use one route-key. but it is out from different consumer. why not be out from one consumer?

**Comment by michaelklishin** [comment]
Can you be more specific, e.g. post your code? I'm not sure I understand what you're doing and what your expectations are.

**Comment by luzi2000** [comment]
int main()
{
  Channel::ptr_t channel;
  channel = Channel::Create("localhost");
  channel->DeclareExchange("main_sharding","x-modulus-hash",false,true);
  int i=0;
  while(true){
    i+=1;
    BasicMessage::ptr_t the_message = BasicMessage::Create("341235345234534645623453245324");
                                     
    channel->BasicPublish("main_sharding",lexical_cast<string>(i%2),the_message,false,false);
    cout<<i<<endl;
  }

**Comment by luzi2000** [comment]
```cpp
int main(int argc,char** argv)
{
  Channel::ptr_t channel;

  channel = Channel::Create("localhost");

  channel->DeclareExchange("main_sharding","x-modulus-hash",false,true);

  vector<string> cs;
  for(int i=0;i<lexical_cast<int>(argv[1]);i++){
    channel->BasicConsume("main_sharding",lexical_cast<string>(i));
    cs.push_back(lexical_cast<string>(i));
  }

  while(true){
    for(int i=0;i<cs.size();i++){
      string& c=cs[i];
      try{
        Envelope::ptr_t env;
        channel->BasicConsumeMessage(c, env, 0);
        if(env){

          std::cout<<c<<":"<<env->Message()->Body()<<std::endl;
        }
      }
      catch(AmqpException& e){
        std::cout<<e.what()<<std::endl;
      }
    }
  }

}


```

**Comment by luzi2000** [comment]
@michaelklishin code like that

**Comment by michaelklishin** [comment]
OK, and what your expectations are, and what's the observed behaviour?

**Comment by luzi2000** [comment]
sudo rabbitmqctl set_policy "3_shard" "main_sharding" "{\"shards-per-node\": 10, \"routing-key\": \"4321\"}"

**Comment by michaelklishin** [comment]
Does `BasicConsumeMessage` use `basic.get` or `basic.consume` protocol method? It makes no sense to use `basic.consume` in a `while(true)` loop.

**Comment by luzi2000** [comment]
I think the same route-key should be out to the same consumer.

**Comment by michaelklishin** [comment]
From the docs:

```
The plugin provides a new exchange type "x-modulus-hash" that will use the traditional hashing technique applying to partition messages across queues.

The "x-modulus-hash" exchange will hash the routing key used to publish the message and then it will apply a Hash mod N to pick the queue where to route the message, where N is the number of queues bound to the exchange. This exchange will completely ignore the binding key used to bind the queue to the exchange.
```

See also #5. I assume what you're looking for is the consistent hash exchange, not this plugin.

**Comment by michaelklishin** [comment]
Exchanges know nothing about consumers, they only pick queues. It's not unreasonable to expect messages the same routing key value to the same queue but this is not how this plugin works (the goal here is to shard a queue by presenting N "physical" queues as a single logical one).

[Consistent hash exchange](https://github.com/rabbitmq/rabbitmq-consistent-hash-exchange/) does what you're looking for, without doing a lot of other stuff this plugin does.

Admittedly the docs for both are not stellar.

**Comment by luzi2000** [comment]
Oh... Thanks a lot.
